#ifndef AST_TYPES_H
#define AST_TYPES_H

#define AST_PROGRAM "program"
#define AST_DECFUNC "decfunc"
#define AST_DECVAR "decvar"
#define AST_FUNCCALL "funccall"
#define AST_ARGLIST "arglist"
#define AST_PARAMLIST "paramlist"
#define AST_BLOCK "block"
#define AST_ASSIGN "assign"
#define AST_RETURN "return"
#define AST_IF "if"
#define AST_ELSE "else"
#define AST_WHILE "while"
#define AST_BREAK "break"
#define AST_CONTINUE "continue"
#define AST_SUM "+"
#define AST_SUB "-"
#define AST_MUL "*"
#define AST_DIV "/"
#define AST_LT "<"
#define AST_LTE "<="
#define AST_GT ">"
#define AST_GTE ">="
#define AST_EQ "=="
#define AST_NEQ "!="
#define AST_AND "&&"
#define AST_OR "||"
#define AST_NOT "!"

#endif // AST_TYPES_H
